apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-demo
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      bb: web
  minReadySeconds: 10
  strategy:
    rollingUpdate: 
        maxSurge: 1
        maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: bb-site:v2
        image: getting-started
---
apiVersion: v1
kind: Service
metadata:
  name: bb-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001