version: '1'
services:
  tomcat:
   image: tomcat:v1
   build:
    context: ./tomcat
    dockerfile: Dockerfile
   hostname: tc1
   ports:
     - 8081:8080
   networks:
     - mynet 
  apache2:
    image: apache2:v1
    build:
        context: ./apache2
        dockerfile: Dockerfile 
    hostname: apache2
    ports:
     - 8082:80
  lb:
    image: lb:v1
    build:
        context: ./lb
        dockerfile: Dockerfile 
    depends_on:
      - tomcat
      - apache2
    volumes:
      - <path to haprox_backup.cfg>:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 8080:8080
    networks:
      - mynet
networks:
  mynet:
    driver: bridge 